name: hi_netx
description: hi netx
version: 1.0.0
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 4.0.6
  hi_core:
      path: ../hi_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
