name: hi_flutter
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # core
  logger: 1.1.0
  dartx: 1.1.0
  equatable: 2.0.5
  # routerx
  fluro: 2.0.3
  # netx
  dio: 4.0.6
  # cache
  shared_preferences: 2.0.15
  sqflite: 2.0.3+1
  cv: 0.2.8+1
  # dialog
  flutter_spinkit: 5.1.0
  flutter_easyloading: 3.0.5
  # web
  webview_flutter: 3.0.4
  # frame
  cached_network_image: 3.2.1
  flutter_redux: 0.10.0
  redux_epics_hi:
      path: ../redux_epics_hi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0